# Generated by Django 5.2.1 on 2025-05-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('social_image', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('dates', models.JSONField(blank=True, null=True)),
                ('ticketType', models.CharField(blank=True, max_length=100, null=True)),
                ('ticketName', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startSales', models.DateTimeField(blank=True, null=True)),
                ('endSales', models.DateTimeField(blank=True, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
