# Generated by Django 5.2.1 on 2025-05-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active_event_organizer_tickettype_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ] 