# Generated by Django 5.2.1 on 2025-06-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
