# Generated by Django 5.2.1 on 2025-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_quantity_tickettype_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
