# Generated by Django 5.2.1 on 2025-05-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_tickets_event_endsales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='social_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
