# Generated by Django 5.2.1 on 2025-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_cover_image_alter_event_social_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticketName',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticketType',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
