# Generated by Django 5.2.1 on 2025-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
