# Generated by Django 5.2.1 on 2025-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
