# Generated by Django 5.2.1 on 2025-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, help_text='Cloudinary URL for user avatar', max_length=500, null=True),
        ),
    ]
